spring:
  application:
    name: puppies-sync-worker
  
  # Read Database Configuration (for updates)
  datasource:
    url: jdbc:postgresql://localhost:5433/puppies_read
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver

  # Flyway Configuration for Read Store
  flyway:
    url: jdbc:postgresql://localhost:5433/puppies_read
    user: admin
    password: admin123
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    enabled: true

  # RabbitMQ Configuration
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate  # Flyway manages schema
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Server Configuration (for health checks)
server:
  port: 8083

# RabbitMQ Queue Configuration
rabbitmq:
  queue:
    post-events: post.events
    user-events: user.events
  exchange:
    puppies-events: puppies.events

# Logging
logging:
  level:
    com.puppies.sync: DEBUG
    org.springframework.amqp: DEBUG
    org.hibernate.SQL: DEBUG